SystemUI: do not load header bar if boot isn't complete
Sometimes during OOBE this header bar will bind the search widget
before boot is complete. This will cause a force close due to:
java.lang.IllegalStateException: Cannot broadcast before boot completed

CYNGNOS-263

Change-Id: Ib235c4b7af87007ba0d57f89ed79c80fb263eacd
(cherry picked from commit ce30097fcd8b4dbdaa08c965c88826eec3c66351)